version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pass@word1"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
  
  pirateshipcollection:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DbServer=sqlserver
      - DbPort=1433
      - DbUser=sa
      - Password=pass@word1
      - Database=shipDb
    depends_on:
      - sqlserver
  
volumes:
  mssqldata: